version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    
volumes:
  db:
    driver: local