// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SurveyTask.Data;

#nullable disable

namespace SurveyTask.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    [Migration("20231019133807_question-relation-fix-3")]
    partial class questionrelationfix3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SurveyTask.Models.AnswerClass.AnswerDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "1",
                            Order = 1,
                            QuestionId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "2",
                            Order = 2,
                            QuestionId = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "3",
                            Order = 3,
                            QuestionId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Too slow",
                            Order = 1,
                            QuestionId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Just right",
                            Order = 2,
                            QuestionId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Too fast",
                            Order = 3,
                            QuestionId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "1",
                            Order = 1,
                            QuestionId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "2",
                            Order = 2,
                            QuestionId = 3,
                            Value = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "3",
                            Order = 3,
                            QuestionId = 3,
                            Value = 3
                        });
                });

            modelBuilder.Entity("SurveyTask.Models.ClientClass.ClientDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Idea"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Univer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lidl"
                        });
                });

            modelBuilder.Entity("SurveyTask.Models.ProjectClass.ProjectDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Name = "Project 1"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            Name = "Project 2"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 2,
                            Name = "Project 3"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 3,
                            Name = "Project 4"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 3,
                            Name = "Project 5"
                        });
                });

            modelBuilder.Entity("SurveyTask.Models.QuestionClass.QuestionDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "How aligned is the project with the initial scope?",
                            Index = 1,
                            Order = 1,
                            Required = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "How would you rate the current pace of the project?",
                            Index = 1,
                            Order = 2,
                            Required = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "How effective is the current team collaboration?",
                            Index = 1,
                            Order = 3,
                            Required = true,
                            Type = 1
                        });
                });

            modelBuilder.Entity("SurveyTask.Models.AnswerClass.AnswerDb", b =>
                {
                    b.HasOne("SurveyTask.Models.QuestionClass.QuestionDb", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SurveyTask.Models.QuestionClass.QuestionDb", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
